import requests
#test_file = open('/Users/Hunter/Downloads/myfile.txt', 'r')
#test_response = requests.post(test_url, files = {"form_field_name": test_file})

#if test_response.ok:
#    print("upload completed successfully.")
#    print(test_response.text)
#else:
#    print("Something went wrong.")
import time
GMTTime = ("\nGMT: "+time.strftime("%a, %d %b %Y %I:%M:%S %p %Z", time.gmtime()))


import csv
with open('/Users/baseb/Downloads/Source 3.csv', 'w', newline = '') as file:
    writer = csv.writer(file)
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000002", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld", ])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])
    writer.writerow([GMTTime,  "A000001", "Received File from HelloWorld",])