"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TELEMETRY_MAX_BUFFER_SIZE = exports.TELEMETRY_CHANNEL_LISTS = exports.TELEMETRY_CHANNEL_ENDPOINT_META = exports.MAX_SECURITY_LIST_TELEMETRY_BATCH = exports.MAX_ENDPOINT_TELEMETRY_BATCH = exports.MAX_DETECTION_RULE_TELEMETRY_BATCH = exports.LIST_TRUSTED_APPLICATION = exports.LIST_ENDPOINT_EXCEPTION = exports.LIST_ENDPOINT_EVENT_FILTER = exports.LIST_DETECTION_RULE_EXCEPTION = exports.INSIGHTS_CHANNEL = void 0;
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

const TELEMETRY_MAX_BUFFER_SIZE = 100;
exports.TELEMETRY_MAX_BUFFER_SIZE = TELEMETRY_MAX_BUFFER_SIZE;
const MAX_SECURITY_LIST_TELEMETRY_BATCH = 100;
exports.MAX_SECURITY_LIST_TELEMETRY_BATCH = MAX_SECURITY_LIST_TELEMETRY_BATCH;
const MAX_ENDPOINT_TELEMETRY_BATCH = 1_000;
exports.MAX_ENDPOINT_TELEMETRY_BATCH = MAX_ENDPOINT_TELEMETRY_BATCH;
const MAX_DETECTION_RULE_TELEMETRY_BATCH = 1_000;
exports.MAX_DETECTION_RULE_TELEMETRY_BATCH = MAX_DETECTION_RULE_TELEMETRY_BATCH;
const TELEMETRY_CHANNEL_LISTS = 'security-lists-v2';
exports.TELEMETRY_CHANNEL_LISTS = TELEMETRY_CHANNEL_LISTS;
const TELEMETRY_CHANNEL_ENDPOINT_META = 'endpoint-metadata';
exports.TELEMETRY_CHANNEL_ENDPOINT_META = TELEMETRY_CHANNEL_ENDPOINT_META;
const LIST_DETECTION_RULE_EXCEPTION = 'detection_rule_exception';
exports.LIST_DETECTION_RULE_EXCEPTION = LIST_DETECTION_RULE_EXCEPTION;
const LIST_ENDPOINT_EXCEPTION = 'endpoint_exception';
exports.LIST_ENDPOINT_EXCEPTION = LIST_ENDPOINT_EXCEPTION;
const LIST_ENDPOINT_EVENT_FILTER = 'endpoint_event_filter';
exports.LIST_ENDPOINT_EVENT_FILTER = LIST_ENDPOINT_EVENT_FILTER;
const LIST_TRUSTED_APPLICATION = 'trusted_application';
exports.LIST_TRUSTED_APPLICATION = LIST_TRUSTED_APPLICATION;
const INSIGHTS_CHANNEL = 'security-insights-v1';
exports.INSIGHTS_CHANNEL = INSIGHTS_CHANNEL;